import {
   KEY_ASSETS_GENERATOR_FRAME_SETTINGS,
   KEY_ASSETS_GENERATOR_LEGEND_SPLITTER_POS,
   KEY_ASSETS_GENERATOR_SPLITTER_POS,
   KEY_ASSETS_GENERATOR_STEPS_SPLITTER_POS,
   KEY_ASSETS_SPLITTER_POS_PX
} from "../settings/AssetsSettings.jsx";

export const ASSETS_GENERATOR_SPLITTER_KEYS = {
   legend_key: KEY_ASSETS_GENERATOR_LEGEND_SPLITTER_POS,
   main_key: KEY_ASSETS_GENERATOR_SPLITTER_POS,
   steps_key: KEY_ASSETS_GENERATOR_STEPS_SPLITTER_POS,
   section_key: KEY_ASSETS_SPLITTER_POS_PX,
   frame_settings_key: KEY_ASSETS_GENERATOR_FRAME_SETTINGS,
}