import {
   KEY_ASSETS_DETECTOR_FRAME_SETTINGS,
   KEY_ASSETS_DETECTOR_LEGEND_SPLITTER_POS, KEY_ASSETS_DETECTOR_SPLITTER_POS, KEY_ASSETS_DETECTOR_STEPS_SPLITTER_POS,
   KEY_ASSETS_GENERATOR_FRAME_SETTINGS,
   KEY_ASSETS_GENERATOR_LEGEND_SPLITTER_POS,
   KEY_ASSETS_GENERATOR_SPLITTER_POS,
   KEY_ASSETS_GENERATOR_STEPS_SPLITTER_POS,
   KEY_ASSETS_SPLITTER_POS_PX,
   KEY_VIDEO_GENERATOR_FRAME_SETTINGS,
   KEY_VIDEO_GENERATOR_LEGEND_SPLITTER_POS,
   KEY_VIDEO_GENERATOR_SPLITTER_POS,
   KEY_VIDEO_GENERATOR_STEPS_SPLITTER_POS
} from "../settings/AssetsSettings.jsx";
import {
   KEY_TILES_GENERATOR_FRAME_SETTINGS,
   KEY_TILES_GENERATOR_LEGEND_SPLITTER_POS,
   KEY_TILES_GENERATOR_SPLITTER_POS,
   KEY_TILES_GENERATOR_STEPS_SPLITTER_POS,
   KEY_TILES_SPLITTER_POS_PX
} from "../settings/TilesSettings.jsx";
import {
   KEY_STUDY_NODES_FRAME_SETTINGS,
   KEY_STUDY_NODES_LEGEND_SPLITTER_POS,
   KEY_STUDY_NODES_SPLITTER_POS,
   KEY_STUDY_NODES_STEPS_SPLITTER_POS,
   KEY_STUDY_SPLITTER_POS_PX
} from "../settings/StudySettings.jsx";

export const ASSETS_GENERATOR_SPLITTER_KEYS = {
   legend_key: KEY_ASSETS_GENERATOR_LEGEND_SPLITTER_POS,
   main_key: KEY_ASSETS_GENERATOR_SPLITTER_POS,
   steps_key: KEY_ASSETS_GENERATOR_STEPS_SPLITTER_POS,
   section_key: KEY_ASSETS_SPLITTER_POS_PX,
   frame_settings_key: KEY_ASSETS_GENERATOR_FRAME_SETTINGS,
}

export const ASSETS_DETECTOR_SPLITTER_KEYS = {
   legend_key: KEY_ASSETS_DETECTOR_LEGEND_SPLITTER_POS,
   main_key: KEY_ASSETS_DETECTOR_SPLITTER_POS,
   steps_key: KEY_ASSETS_DETECTOR_STEPS_SPLITTER_POS,
   section_key: KEY_ASSETS_SPLITTER_POS_PX,
   frame_settings_key: KEY_ASSETS_DETECTOR_FRAME_SETTINGS,
}

export const VIDEO_GENERATOR_SPLITTER_KEYS = {
   legend_key: KEY_VIDEO_GENERATOR_LEGEND_SPLITTER_POS,
   main_key: KEY_VIDEO_GENERATOR_SPLITTER_POS,
   steps_key: KEY_VIDEO_GENERATOR_STEPS_SPLITTER_POS,
   section_key: KEY_ASSETS_SPLITTER_POS_PX,
   frame_settings_key: KEY_VIDEO_GENERATOR_FRAME_SETTINGS,
}

export const TILE_GENERATOR_SPLITTER_KEYS = {
   legend_key: KEY_TILES_GENERATOR_LEGEND_SPLITTER_POS,
   main_key: KEY_TILES_GENERATOR_SPLITTER_POS,
   steps_key: KEY_TILES_GENERATOR_STEPS_SPLITTER_POS,
   section_key: KEY_TILES_SPLITTER_POS_PX,
   frame_settings_key: KEY_TILES_GENERATOR_FRAME_SETTINGS,
}

export const STUDY_NODES_SPLITTER_KEYS = {
   legend_key: KEY_STUDY_NODES_LEGEND_SPLITTER_POS,
   main_key: KEY_STUDY_NODES_SPLITTER_POS,
   steps_key: KEY_STUDY_NODES_STEPS_SPLITTER_POS,
   section_key: KEY_STUDY_SPLITTER_POS_PX,
   frame_settings_key: KEY_STUDY_NODES_FRAME_SETTINGS,
}